/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCropRouteImport } from './routes/_authenticated/crop'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiseaseRouteImport } from './routes/_authenticated/disease'
import { Route as AuthenticatedFarm3dRouteImport } from './routes/_authenticated/farm-3d'
import { Route as AuthenticatedHotspotsRouteImport } from './routes/_authenticated/hotspots'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedOfficialRouteImport } from './routes/_authenticated/official'
import { Route as AuthenticatedPestsRouteImport } from './routes/_authenticated/pests'
import { Route as AuthenticatedWaterRouteImport } from './routes/_authenticated/water'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCropRoute = AuthenticatedCropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiseaseRoute = AuthenticatedDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarm3dRoute = AuthenticatedFarm3dRouteImport.update({
  id: '/farm-3d',
  path: '/farm-3d',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotspotsRoute = AuthenticatedHotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficialRoute = AuthenticatedOfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPestsRoute = AuthenticatedPestsRouteImport.update({
  id: '/pests',
  path: '/pests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaterRoute = AuthenticatedWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/crop': typeof AuthenticatedCropRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disease': typeof AuthenticatedDiseaseRoute
  '/farm-3d': typeof AuthenticatedFarm3dRoute
  '/hotspots': typeof AuthenticatedHotspotsRoute
  '/live': typeof AuthenticatedLiveRoute
  '/official': typeof AuthenticatedOfficialRoute
  '/pests': typeof AuthenticatedPestsRoute
  '/water': typeof AuthenticatedWaterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/crop': typeof AuthenticatedCropRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disease': typeof AuthenticatedDiseaseRoute
  '/farm-3d': typeof AuthenticatedFarm3dRoute
  '/hotspots': typeof AuthenticatedHotspotsRoute
  '/live': typeof AuthenticatedLiveRoute
  '/official': typeof AuthenticatedOfficialRoute
  '/pests': typeof AuthenticatedPestsRoute
  '/water': typeof AuthenticatedWaterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/crop': typeof AuthenticatedCropRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disease': typeof AuthenticatedDiseaseRoute
  '/_authenticated/farm-3d': typeof AuthenticatedFarm3dRoute
  '/_authenticated/hotspots': typeof AuthenticatedHotspotsRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/official': typeof AuthenticatedOfficialRoute
  '/_authenticated/pests': typeof AuthenticatedPestsRoute
  '/_authenticated/water': typeof AuthenticatedWaterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/crop'
    | '/dashboard'
    | '/disease'
    | '/farm-3d'
    | '/hotspots'
    | '/live'
    | '/official'
    | '/pests'
    | '/water'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/crop'
    | '/dashboard'
    | '/disease'
    | '/farm-3d'
    | '/hotspots'
    | '/live'
    | '/official'
    | '/pests'
    | '/water'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/crop'
    | '/_authenticated/dashboard'
    | '/_authenticated/disease'
    | '/_authenticated/farm-3d'
    | '/_authenticated/hotspots'
    | '/_authenticated/live'
    | '/_authenticated/official'
    | '/_authenticated/pests'
    | '/_authenticated/water'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crop': {
      id: '/_authenticated/crop'
      path: '/crop'
      fullPath: '/crop'
      preLoaderRoute: typeof AuthenticatedCropRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disease': {
      id: '/_authenticated/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof AuthenticatedDiseaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm-3d': {
      id: '/_authenticated/farm-3d'
      path: '/farm-3d'
      fullPath: '/farm-3d'
      preLoaderRoute: typeof AuthenticatedFarm3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspots': {
      id: '/_authenticated/hotspots'
      path: '/hotspots'
      fullPath: '/hotspots'
      preLoaderRoute: typeof AuthenticatedHotspotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/official': {
      id: '/_authenticated/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof AuthenticatedOfficialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pests': {
      id: '/_authenticated/pests'
      path: '/pests'
      fullPath: '/pests'
      preLoaderRoute: typeof AuthenticatedPestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/water': {
      id: '/_authenticated/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof AuthenticatedWaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCropRoute: typeof AuthenticatedCropRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiseaseRoute: typeof AuthenticatedDiseaseRoute
  AuthenticatedFarm3dRoute: typeof AuthenticatedFarm3dRoute
  AuthenticatedHotspotsRoute: typeof AuthenticatedHotspotsRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedOfficialRoute: typeof AuthenticatedOfficialRoute
  AuthenticatedPestsRoute: typeof AuthenticatedPestsRoute
  AuthenticatedWaterRoute: typeof AuthenticatedWaterRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCropRoute: AuthenticatedCropRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiseaseRoute: AuthenticatedDiseaseRoute,
  AuthenticatedFarm3dRoute: AuthenticatedFarm3dRoute,
  AuthenticatedHotspotsRoute: AuthenticatedHotspotsRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedOfficialRoute: AuthenticatedOfficialRoute,
  AuthenticatedPestsRoute: AuthenticatedPestsRoute,
  AuthenticatedWaterRoute: AuthenticatedWaterRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
